common.sh
Main goal is to resolve #102.
Also, "lost" documentation strings are ported from the abandoned PR #97 and some strings have been added by me; where I dared to guess.
To view and/or generate doc with `shellfu-doc` (missing features mentioned in the issue#102 are already implemented):
1. install package *shellfu-devel* from [my Fedora Copr][1].
[1]: https://copr.fedorainfracloud.org/coprs/amahdal/shellfu/
2. `shellfu-doc ./common.sh` to view manpage directly
3. `shellfu-doc -e pod ./common.sh` to export to POD (for use with eg. pod2man)
Also you can e.g.:
shellfu-doc --help
shellfu-doc --lsfun ./common.sh
shellfu-doc --lsvar ./common.sh
shellfu-doc -e markdown ./common.sh | Markdown > common.html
=> Shellfu style for Bash modules

common.sh, preup/script_api.py
Bash API uses '[unknown]' so Python API should do the same.
=> Improve component name placeholder

common.sh
This is a functional change; now we re-set these global variables every
time someone uses any of those functions.  Of course, nobody should, but
in theory, someone could rely on this (due to strange bug or naming
conflict).
=> Don't pollute Bash environment with variables

common.sh, preup/script_api.py
In Python, it's convention to name private stuff starting with underscore.
In Bash, shellfu-doc respects this convention as well, so this will hide
these functions from a generated manpage or listing.
=> Hide generic logging message functions

common.sh, preup/script_api.py, preup/xccdf.py, preup/xml_manager.py, preup_ui/report/processing.py, tests/FOOBAR6_7/dummy/needs_action/dummy_failed.sh, tests/FOOBAR6_7/dummy/needs_action/solution.txt, tests/FOOBAR6_7/dummy/needs_inspection/dummy_failed.sh, tests/FOOBAR6_7/dummy/needs_inspection/solution.txt, tests/test_inplace_risks.py
Note: this is addressed by [bug 1361378][1] in downstream.  Following text is taken from there.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1361378
Description of problem
======================
Currently there are two issues with logging from modules:
*  Risks use prefix "INPLACERISK:" that is not suitable for migration
scenarios.
*  Other log messages use format that is hard to filter out.
Together with bug 1309491 (openscap merges stderr to stdout), this makes
it hard to catch situations when scripts leak some info outside intended.
For example, "leaking" grep as in bug 1356811, sntax errors or errors
thrown by external utilities called by modules are all problems
that could be easily checked by tests *if* the formatting was more
filtering-friendly.
Proposal
========
For logging …
=> Improve logging format

common.sh, preup/script_api.py
In Python API, this ilegally calls internal log function.
In Bash API, this is a stray output.
In both cases `$pwd` variable exists only for the log, so removing that
as well.
=> Remove forgotten echo/log

common.sh, preup/script_api.py
This solves multiple (not all) issues discussed in last commenrt in rhbz#1334903.
Bash part tested with current downstream build (replaced common.sh, ran test).
Please see individual commits for more details.
=> More robust & strict hook deployment

preup/script_api.py
This syntax is incorrect; it means log error with text *literally*
"Unknown hook option '%s'" as if related to component deploy_name.
=> Fix error message formatting

preup/script_api.py
When there's less than 1 arg, `arg[0]` is not a valid expression and
will raise IndexError.  That's what happended in cases when either script
name or both script name and hook type were not specified.
This commit changes the error handling so that it will actually work.
=> Fix argument parsing

data/report/complex/xccdf-report-impl.xsl, data/report/simple/sce-report.xsl, data/report/simple/xccdf-report.xsl
Openscap will support split of stderr and stdout outputs instead
of one merged output as was before. XSL files are modified
to correctly handle this change and in addition are still compatible
with the old one.
In addition
- stdout is presented as "Additional info"
- stderr is presented as "Logs"
for better description for reader. And tabs were replaced by spaces.
TODO: Old-style report could be modified yet for better
visualisation of these two "signs" - like changed color
or something like that. But that's minor change to future.
=> fix XSL files to support new version of OpenSCAP

kickstart/finish.sh, preup/kickstart/application.py, preup/kickstart/cli.py, preup/settings.py, preup/utils.py, tests/test_kickstart.py
This Pull Request will execute user defined scripts mentioned in "postinstall.d" directory on migrated system.
User/admin is inform in case "postinstall.d" is empty.
~~~
You did not specify any postinstall scripts. Include them to /root/preupgrade/postinstall.d 
Do you want to continue with kickstart generation without postinstall scripts? (Y/n)
~~~
=> Implementation postmigrate.d directory

doc/api-consistency.md
In order to help keep behavior of Python API consistent with Bash API
and vice versa, this document tries to recommend practices and styles
"from both worlds".
=> Add guide for API consistency

common.sh
Replace with -r which has the same meaning (extended regexp)
This option actually breaks execution of every module on RHEL 5.
=> Don't use -E sed option (not working on RHEL 5)

man/preupgrade-assistant-api.1, preupg/ui/report/models.py, preupg/ui/report/processing.py, preupg/ui/report/south_migrations/0001_initial.py, preupg/ui/templates/report/test.html, preupg/xmlgen/script_utils.py, tests/FOOBAR6_7/dummy/failed/dummy_failed.sh
And also from UI and man page.
This PR continues upon the already merged PR https://github.com/upgrades-migrations/preupgrade-assistant/pull/195.
Resolves: [rhbz#1372871](https://bugzilla.redhat.com/show_bug.cgi?id=1372871)
=> remove 'component' from generated modules and tests

preupg/kickstart/plugins/packages.py
There's a typo which prevents reading special_pkg_list - that's a list of packages that modules decide to be added to kickstart.
=> Fix typo causing incomplete kickstart

common.sh
Previously some log functions in bash API accepted multiple parameters by "$@", however
main '_log' function ignore them. But log_* functions accept
only one argument.
Replace of "$@" by "$1" in log_* functions to avoid another confusion. Funcionality will be then synced with API for Python.
=> sync log_* functions in API for BaSH

data/templates/xccdf_template.xml, packaging/sources/preupgrade-assistant-scripts.patch
- the text in XCCDF template updated to be comprehensible
- the RedHat to Red Hat change is related to [rhbz#1330454](https://bugzilla.redhat.com/show_bug.cgi?id=1330454)
=> RedHat -> Red Hat; remove RedHat from XCCDF template

packaging/preupgrade-assistant.spec, packaging/sources/crossarch_migration_support_check.patch
- check whether there are data in preupgrade-asssistant-*-data pkg
that are required for a migration path from one architecture to
another (i.e. when --dst-arch option is used)
Related: rhbz#1414388
=> Check for required data for crossarch migration

preupg/utils.py
The old version created temp file (used as cache between oscap and our
log file) file "manually" as random single-letter named file under /tmp
(explicitly).  Furthermore, these files (2 of them are created with each
preupg run) are not removed afterwards.
This is unsafe and messy.  Unsafe, because adversary could easily guess
temp file name and write to it between oscap ends and file is re-read
again.  Messy because we're leaving "anonynous" random files in temp.
The fix makes use of standard Python function `tempfile.mktemp()` to
handle the tempfile creation.  While the fiename is less predictable,
this is still not completely safe: `mktemp()` still suffers from the
race-condition risk.  mktemps() from the same module does solve it but
that's not usable with ProcessHelper/FileHelper, …
=> Fix tempfile handling

packaging/preupgrade-assistant.spec
Without this, when creating an RPM on a system with Python 2.4 (RHEL 5) there were syntax errors because it tried to byte-compile the UI source code in the %install section (and UI is not to be part of RHEL 5 package).
=> Fix rpm package building with Python 2.4

packaging/sources/preupgrade-assistant-scripts.patch
In the patched data/preassessment/scripts.txt file on RHEL system
was previously use of "chkconfig" without options. On RHEL 6 system
generates same output as with "--list" option. However on RHEL 5
prints just usage.
As the "chkconfig --list" output is what is really expected output,
use this instead of simple chkconfig without options.
=> fix patch for data/preassessment/scripts.txt

tests/__init__.py, tests/test_generation.py, tests/test_xml.py
- run test_generation.py
- it was not present in the test suite previously
- fix the tests so that they don't alter the original source code
- that was causing that the other tests were failing as
they were not expecting the source code altered
=> Fix existing tests

packaging/sources/preupgrade-assistant-scripts.patch
In the patched data/preassessment/scripts.txt file on RHEL system
the "df" utility is used without "-P" option for POSIX format, that
guarantees each item of the output will be printed on the one line
only without wrapping. Otherwise the output can be wrapped
and generated data will be broken or incomplete in better case. This
commit fixes use of "df".
In addition, the "find" utility of version 4.2.27 (or lesser), does
not contain option "-executable", originally used in the scripts.txt
file. This is problematic on RHEL 5 system (or just systems which
uses too old find option). Instead of this, should be used:
"-perm /111"
which is compatible with new version of the utility too.
** this should be finally the final patch of the "scripts.txt" file **
=> fix(2) patch for data/preassessment/scripts.txt

bin/preupg, preupg/report_parser.py, preupg/xccdf.py
- somewhere there is "return codes" used, on another places it's return state or return value - make it consistent
Related: rhbz#1414359
=> Make naming of "return codes" consistent

packaging/preupgrade-assistant.spec, packaging/sources/preupgrade-assistant-python-2.4.patch, packaging/sources/preupgrade-assistant-xml-logs.patch
Previously there were use of python3 "print" function rewrite to use of python2 print function. But the rewrite changed the output, as there was used stdout instead of stderr sometimes; sometimes was produced string with two newlines ending instead of one newline character. This is fixed now.
The old openscap doesn't provide separately stderr and stdout output of each module and both merges into the stdout. Stderr is usually empty (or more precisely, contains whitespaces only).
To be more compatible with possible tests written on RHEL 6 system, merge stdout and stderr outputs in the results.xml file together as stderr and stdout remove.
I am not sure about possible outputs of OpenSCAP for all situations, so solution seems more ugly than it has to be.
=> RHEL5: fix generating of report file

packaging/sources/preupgrade-assistant-python-2.4.patch
Fix handling exceptions:
- python 2.4 does not support "except <Exc> as <var>:", it needs to be "except <Exc>, <var>:"
=> fix python 2.4 patch

preupg/kickstart/application.py
- set autopart to let the new system set up partitions automatically
- comment out custom partitioning commands
Related:
- https://bugzilla.redhat.com/show_bug.cgi?id=1414408
- https://bugzilla.redhat.com/show_bug.cgi?id=1414341
=> Autopart instead of custom partitioning in kickstart

packaging/sources/preupgrade-assistant-six.patch, preupg/utils.py
Check of the "int" type is much more transparent and issue-proof
then checking of variable text type.
In addition, it provides bug on some old systems, where the "str"
or the "unicode" type was used, based on unspecified settings
of system.
=> FileHelper.check_file: check type "int" instead of text types

data/templates/preupgrade.ks, preupg/kickstart/application.py
- it may pose a security risk to put the root password into the
kickstart - use a placeholder instead. User will need to fill
in the password first before using the kickstart
- set the default hashing algorithm for user passwords to the
strong sha-512.
=> mitigate security issues in kickstart

preupg/script_api.py
The *star* import of API for python modules doesn't include
the add_pkg_to_kickstart. (Fixed)
=> add fce add_pkg_to_kickstart into __all__ in py API

packaging/preupgrade-assistant.spec
In spec file, there was a missing GPLv2 license under which the bundled pykickstart-1.74.20 is licensed.
=> Add GPLv2 license of the bundled pykistart to spec

data/templates/postmigrate.sh
- unpack tarball with '--selinux' option to keep original selinux
context
- modified and added log messages
- remove creating of ".diff" files when restore cleanconf configs
- WHY:
- the files would be overwritten when some configuration files
have same names but different paths
- the log file was messy because of trailing diff output
- admin is able to create diff of the modified files
very simply
- backup original files with suffix .preupg_save instead of .rpmsave
which could be rewritten during installation/update of new
packages
- fix paths for
- create symlinks for other important directories
- added: noauto_postupgrade.d, postmigrate.d
(we can discuss creation of symlinks for all 'main' directories
in /root/preupgrade)
=> kickstart: fix postmigrate template for kickstart

preupg/report_parser.py
The OpenSCAP put whole stdout/stderr into the result.xml directly
so we are not able to handle these outputs. In case that the BEL
character is produced by some utility (it happened already), parsing
of XML file fails.
NOTE: Some XML libraries handle it already, but not the one, used
by the PA, mainly on older systems
=> remove the BEL characters when reloads XML file

preupg/kickstart/application.py
- when generating kickstart there was a question to
the user whether to proceed in case there were no
scripts in the /root/preupgrade/postmigrate.d
directory. This directory was supposed to be used
by the user if they wanted to add any custom script
to be run after the migration. However it doesn't
work - if the user adds any script there, it doesn't
get into the generated kickstart. Since this feature
is not documented anywhere it's best to remove the
question for now.
=> remove question with no postmigrate.d script

packaging/sources/preupgrade-assistant-python-2.4.patch, preupg/application.py, preupg/settings.py
- there was a message at the beginning of the assessment
that warned user to backup the system before doing
a system upgrade. This warning makes no sense if the
user has specified that they want to perform migration.
- move the message from before doing the assessment to
when the assessment is finished - as one of the last
messages.
=> move warning about backing up the system

preupg/script_api.py
Otherwise the condition that follows cannot pass, effectively disabling
list mode for DIST_NATIVE.
Resolves rhbz#1384270.
=> Strip whitespace from DIST_NATIVE list

preupg/settings.py
**Problem:**
Preupgrade Assistant tools in this moment depend on hardcoded paths
from setting.py including data_dir, which points to
'/usr/share/preupgrade/data'. When PA isn't installed on the system
and developer wants to test a new code(e.g. run xccdf-compose) he
needs to edit setting.py in order to change data_dir variable.
**Solution:**
To be able to override this data_dir variable with environment
variable "PREUPG_DATA_DIR" instead of changing setting.py
=> Add possibility to change data_dir with env variable

preupg/xmlgen/xml_tags.py
When generating module set for Preupgrade Assistant using _tools/preupg-xccdf-compose_, XML parse errors were occuring.
Error example:
```
Encountered a parse error in file /home/mbocek/.../RHEL5_7-results/services/pki/pki-ca/group.xml.
Details: mismatched tag: line 42, column 8
```
It was due to unclosed HTML tags in generated group.xmls.
=> Fix generating Preupgrade Assistant modules

packaging/preupgrade-assistant.spec
- bundled_pykickstart_dirname variable should have been
removed in previous commits removing RHEL 5 code but was
left here by mistake
=> Remove obsolete variable from spec

preupg/xmlgen/xml_tags.py, preupg/xmlgen/xml_utils.py, tests/test_xml.py
- without it, the default ns0 is used, which is openscap namespace
and this namespace doesn't define html tags - that leads to crash
during the xml parsing
=> Revert back removed xhtml namespace

preupg/application.py
In one of the previous commits (https://github.com/upgrades-migrations/preupgrade-assistant/commit/817fe90d50f022db36db5a38b96faef11c2c23ad#diff-cd214281061a49f12a09f465b45bc87bR395) an issue was introduces when _.items()_ function was misplaced - used on a string instead of a list.
It was causing an error:
```
140/140 ...done    (The NIS server configuration file)
The assessment finished (time 02:58s)
Traceback (most recent call last):
File "/usr/bin/preupg", line 19, in main
return_code = app.run()
File "/usr/lib/python2.6/site-packages/preupg/application.py", line 746, in run
retval = self.scan_system()
File "/usr/lib/python2.6/site-packages/preupg/application.py", line 520, in scan_system
self.run_third_party_modules(third_party_dir_name)
File …
```
=> Fix running third party modules

preupg/application.py
Related RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1332775
- incorrect advice was printed in the error message when not-installed module set name was used with --scan option
=> Improve error message with wrong module set

preupg/application.py, preupg/scanning.py
Now when running the assessment, the execution time of each module is printed next to the title of the module. Example:
```
086/137 ...done    (Binaries to be rebuilt) (time: 00:24s)
```
- related: https://bugzilla.redhat.com/show_bug.cgi?id=1392026
=> Print each module exec time during the assessment

preupg/application.py
- When more than one module set was available, --list-rules option was not working
- Related:
- https://bugzilla.redhat.com/show_bug.cgi?id=1418509
- Issue https://github.com/upgrades-migrations/preupgrade-assistant/issues/225
=> Fix listing rules in case of multiple modules sets

preupg/application.py
Fixes running Preupgrade Assistant when running it with just a _-u_ option:
`preupg -u http://hostname:8099/submit`
This is a basic command that used to work and is documented on many places. So this is a high priority one.
Resolves: [rhbz#1391968](https://bugzilla.redhat.com/show_bug.cgi?id=1391968)
=> Allow using -u option without -r

man/preupg.1, preupg/application.py
Return value of the function that uploads results (_Application.upload_results()_) to the WEB-UI server was not checked so Preupgrade Assistant didn't provide information to the user when the upload failed.
Related: rhbz#[1391968](https://bugzilla.redhat.com/show_bug.cgi?id=1391968)
=> Return code 28 instead of 0-2 when upload fails

doc/module_writing_tutorial/README.md, preupg/utils.py, tests/FOOBAR6_7/properties.ini, tests/test_preupg.py
Python ConfigParser module's default implementation uses lower case. So for
better readability and to prevent any misunderstandings change from
lowerCammelCase to snake_case.
=> Change properties ini options to snake_case

preupg/xmlgen/compose.py, preupg/xmlgen/oscap_group_xml.py, preupg/xmlgen/xml_utils.py, tests/test_generation.py, tests/test_xml.py
When run:
```
preupg-xccdf-compose RHEL6_7
```
tag generated in group.xml looks like:
```xml
<value>SCENARIO/backup/bacula</value>  
```
but when run:
```
preupg-xccdf-compose moduleDir
```
tag looks like:
```xml
<value>SCENARIO/root/moduleDir-results/backup/bacula</value>
```
This concerns multiple tags through xml files not only one showed above.
=> Dir name dependent tags in generated xml files with xccdf-compose

preupg/application.py, preupg/creator/settings.py, preupg/creator/ui_helper.py, preupg/utils.py, preupg/xmlgen/compose.py, tests/test_creator.py
Based on #286. 
Preupgrade-content-creator was looking for a specific upgrade path,
replace this behavior with no dependency on directory name and also add
properties.ini into new created module set directory.
In compose.py check for existing properties.ini file in exitsting
module set directory instead of in directory with '-results' postfix.
=> Fix getting right module set directory

data/report/complex/xccdf-report-impl.xsl, data/templates/xccdf_template.xml, preupg/application.py, preupg/report_parser.py, preupg/settings.py, preupg/utils.py, preupg/xccdf.py, preupg/xmlgen/xml_tags.py, preupg/xmlgen/xml_utils.py, tests/generated_results/inplace_combined_risk_test.xml, tests/generated_results/inplace_risk_test.xml, tests/test_preupg.py
Preupgrade Assistant was setting the CPE platform (standardized OS identification) in the module set _all-xccdf.xml_.
Also, in case the _--contents_ option was used, Preupgrade Assistant was setting the CPE platform in the original module set _all-xccdf.xml_, which is  definitely not OK.
There is no need for the CPE in the report, the information doesn't have any value for the user. And when user faces a problem with the tool, the Red Hat support requests _sosreport_ which contains the identification of the OS.
Related issue: #247
=> Remove CPE platform from the result report

preupg/creator/settings.py, preupg/creator/ui_helper.py
Message is obsolete because content-creator itself is taking care of
options in properties.ini.
=> Remove properties ini msg in content-creator

common.sh, man/preupgrade-assistant-api.1, preupg/script_api.py
- remove _RESULT_FAILED_ and _check_root()_ from bash API
- _check_root_ is not needed as the Preupgrade Assistant is always run as root
- _RESULT_FAILED_ is not present in Python and the existing _RESULT_FAIL_ is sufficient
- remove _exit_failed()_ from python API
- the _exit_failed()_ is not in bash API and the existing _exit_fail()_ is sufficient
This resolves #199 and resolves #164
=> Remove symbols from python and bash APIs

preupg/application.py, preupg/utils.py, preupg/xmlgen/oscap_group_xml.py, tests/test_preupg.py
- Remove get_module_set_dirname method from PA.
- Fix generating list_rules file: rules have wrong names e.g.:
from: `xccdf_preupg_rule_general_check` 
fixed to : `xccdf_preupg_rule_selinux_general_check`
- Fix --contents option: when option is used PA fails on finding `properties.ini` because wrong path. Use normpath in order to do the check.
=> Remove get_module_set_dirname, fix list_rules and --contents

.landscape.yaml, README.md
- [Landscape](https://landscape.io) has been integrated more with this project, it will now report any static analysis code issues for every PR. This change comes with a different code health icon URL.
- Also, switch off warnings about missing documentation strings.
Resolves https://github.com/upgrades-migrations/preupgrade-assistant/issues/309
=> Fix Landscape health icon

data/report/simple/sce-report.xsl, data/report/simple/xccdf-report.xsl, preupg/application.py, preupg/report_parser.py
**_result.xml_ tweaks:**
- Removed whitespace at the beginning and end of each module _stdout_ and _stderr_ (Additional info` and `Logs`).
- _stdout_ of modules is removed from the  _result.xml_ when it is empty, however _stderr_ wasn't. Now both of them are removed when empty.
**Simple style _result.html_ tweaks:**
- _stdout_ and _stderr_ are now left in the report no matter what the result of a module is. Before the output was not shown for `pass` and `fixed` results. The behaviour is now consistent with the complex report style.
- Remove an excessive newline from the beginning of each module _stdout_ and _stderr_ (`Additional info` and `Logs`).
=> Fix logs and additional output in result file

preupg/common.py
During work on another PR, I found out this is not used anywhere.
=> Remove dead code (function never used)

preupg/application.py
Preupgrade Assistant was corrupting module set _all-xccdf.xml_ in case the module set path was specified through the _--contents_ option.
Resolves rhbz#[1368823](https://bugzilla.redhat.com/show_bug.cgi?id=1368823)
Resolves #247
=> Do not corrupt custom module set all-xccdf.xml

preupg/ui/report/processing.py, preupg/ui/report/service.py, preupg/ui/report/tests.py, preupg/ui/report/views.py
Any link to a file or folder in the Web UI did not work. There were three problems:
- During the upload to the UI, the tarball with the system assessment results was extracted. However, all content in the tarball is under the _preupg_results-\<timestamp\>_ subfolder - the Web UI does not expect this subfolder. Now, just the content that is under this subfolder is extracted.
- Previously, it was possible to display only files (to which there was a link in the Web UI report), not folders. Now, if the user clicks on a link to a folder, the Web UI displays the content of the folder.
- It was possible to view **the original** HTML report through Web UI. Within the report there might be links to files & folders that work correctly in its default location (_/root/preupgrade_) but not in the Web …
=> Fix links to files & dirs in Web UI reports

packaging/preupgrade-assistant.spec
An rpmbuild option --define "build_ui 0" now does the trick.
=> Option to skip building UI

packaging/preupgrade-assistant.spec, preupg/application.py, preupg/utils.py
Old OpenSCAP doesn't support new complex report style that is used
by default by the Preupgrade Assistant tool. Enforce the simple
style of report (like with --old-report-style) when version of
installed OpenSCAP is lower then 1.2.7. In case of enforced fallback
to the simple style of report log message to inform the user.
Additionaly change requirements to openscap* >= 0:1.0.10
=> Support older versions of the OpenSCAP

preupg/creator/ui_helper.py
preupg-content-creator was adding `solution` key to the module INI.
The module's solution file has to be named _solution.txt_ and the solution key is not supposed to be in the module INI anymore.
Related: https://github.com/upgrades-migrations/preupgrade-assistant/pull/311
=> Creator: do not insert 'solution:' to module.ini

preupg/utils.py
This method:
- is dead/not used code
- obsolete because the module set dir is retrieved by _application.py_ method `_get_default_module_set()`
=> Remove unused/obsolete get_upgrade_dir_path()

packaging/preupgrade-assistant.spec
At least `%post ui` script and `%files ui` rely on Apache being installed
(or at least its user/group being present).
So far this has *mostly* worked because it already Requires mod_wsgi,
which does pull in httpd, but that's not necessarily true for all
mod_wsgi packages; for example version of mod_wsgi shipped with Satellite
does not require it.
At any rate, correct way is to always declare dependencies directly on
things that we use.
=> Add missing Requires: httpd

preupg/application.py
The "placeholer" was not replaced, because XmlManager expects path
to the copied module set (/root/preupgrade/RHEL6_7) instead
of dirname (RHEL6_7).
=> Use the path to the copied module set directory instead of dirname

preupg/xml_manager.py
These variables actually hold the whole path and not just a dirname. It has already caused confusion and error - see https://github.com/upgrades-migrations/preupgrade-assistant/pull/340.
=> Rename variables to include 'path' instead of 'dir'

preupg/application.py, preupg/settings.py, preupg/utils.py, preupg/xmlgen/compose.py
Enable processing of third party modules. Original solution has been completely dropped (with additional dead code) because it was too messy and buggy. Current solution regenerates original XCCDF compose under `assessment_results_dir` from the used module-set. Limitation of this solution is processing of the third party modules in group with the others instead of previous idea to process them after the *main* set of modules is processed.
~~TODO~~ (Done):
- handle situation when src and dst paths for XCCDFCompose are same. Currently the dst path is alwasy removed when exist  and this could lead into lost of original modules. This is not possible now, but it would in future. It will be better to handle it now to prevent such situation in future. Possible solution
-  is to ignore given dst …
=> Fix running 3rd party modules

README.md, test-requirements.txt
This PR has been triggered by an error in our CI environment in which installation of pylint (actually its dependency) failed and caused that our unit tests were not executed.
The removal of the pip packages installation is fine, see below:
- we do not use pylint anymore (we use landscape.io instead)
- ordered_set is not needed on RHEL 6 (it may be needed with newer
versions of pykickstart but then it's a dependency of that package)
- six doesn't need to be installed through pip, there's a package for
that on RHEL 6
I haven't removed the `pylintrc` file as it should be picked up by Prospector - one of the tools called by Landscape.
=> Remove not needed pip test requirements

packaging/sources/preupgrade-assistant-scripts.patch
Add `-type f` argument for `find` so that it does not print symlinks
that might point to non-local file systems
=> The list of files should contain only executable files, not symlinks

preupg/script_api.py, preupg/utils.py
The Python API function `check_rpm_to` was calling `get_file_content()` (with UTF-8 decoding flag being True) that **had no purpose there** and it was causing tracebacks for users when the _executable.log_ (`VALUE_EXECUTABLES`) file contained some non-UTF-8 characters.
```
Traceback (most recent call last):
File "/root/preupgrade/RHEL6_7/system/RemovableMedia/check", line 24, in &lt;module&gt;
check_rpm_to (check_rpm="",check_bin="lsblk")
File "/usr/lib/python2.6/site-packages/preupg/script_api.py", line 526, in check_rpm_to
lines = FileHelper.get_file_content(VALUE_EXECUTABLES, "rb", True)
File "/usr/lib/python2.6/site-packages/preupg/utils.py", line 186, in get_file_content
data = f.read() if not method else f.readlines()
File "/usr/lib64/python2.6/codecs.py", line 679, in readlines …
```
=> Fix reading VALUE_EXECUTABLES file with non-UTF-8 chars

preupg/scanning.py
Ignore stderr when can't get width of terminal. The value is used only for formatting pusposes and default value is still 80.
The get_terminal_width method returns now really the width value. Before it returns only string with height and width.
Resolves: #343
=> Fix issue with redirected stdin

common.sh, preupg/script_api.py
In the set of directories used by PA modules have been several directories without provided paths through the API. Now all paths to significant directories are provided. New paths includes:
- CLEANCONF_DIR - cleanconf directory
- DIRTYCONF_DIR - dirtyconf directory
- PREUPGRADE_SCRIPT_DIR - directory with pre-upgrade scripts processed by RUT
- POSTMIGRATE_DIR - directory with scripts processed during the %post phase of installation of a new system through the generated kickstart
=> Provide paths to all significant directories in PA API
