upgrades-migrations/preupgrade-assistant

man/preupg-content-creator.1
preup/application.py
preup/utils.py
preup_creator/application.py
preup_creator/cli.py
preup_creator/conf.py
preup_creator/settings.py
preup_creator/ui_helper.py
preupg-content-creator

The content creator is mostly done.

Preupg content creator

---

common.sh

Fix syntax error introduced by 7e33cfab

---

common.sh
preup/script_api.py

Add pkg to kickstart via API

---

man/preupg.1
preup/application.py

Updated return values.

---

common.sh
postupgrade.d/postupgrade_hooks.sh
preup/settings.py
preup/utils.py

Implement hook system

---

preup_ui/report/models.py

Fix query set method

---

preup/script_api.py

This looks like it was forgotten from a debugging session.

Remove unnecessary log_error()

---

preup/creator/settings.py

Fix API import in preupg-content-creator

---

preup/creator/settings.py
preup/creator/ui_helper.py

This Pull Request adds a default value in case user did not specify it.

Add default value for check script

---

.travis.yml
README.md
preup/utils.py
preup/xml_manager.py
tests/test_preup.py

This is first draft for Travis-CI

First draft for Travis-CI.

---

common.sh
man/preupg.1
man/preupgrade-assistant-api.1
preup/script_api.py
preup/settings.py
preuputils/xml_utils.py
tests/__init__.py
tests/test_inplace_risks.py

Signed-off-by: Petr Hracek phracek@redhat.com

Remove unknown exit value

---

man/preupg.1

Resolves issue https://github.com/upgrades-migrations/preupgrade-assistant/issues/190

update man page to reflect current exit statuses

---

tools/preupg-create-group-xml

related: [rhbz#1402210](https://bugzilla.redhat.com/show_bug.cgi?id=1402210)

fix incorrect import of xmlgen module

---

common.sh
preupg/script_api.py

- related [rhbz#1372871](https://bugzilla.redhat.com/show_bug.cgi?id=1372871)

remove component name from log message

---

data/preassessment/scripts.txt
doc/README.kickstart

RPMs are signed by DSA cryptographic algorithm. Added patch
and modified specfile for rhel-5 systems.

fix gathering info about all installed packages on RHEL 5

---

packaging/preupgrade-assistant.spec
packaging/sources/preupgrade-assistant-pykickstart.patch
packaging/sources/preupgrade-assistant-six.patch
preupg/kickstart/application.py
preupg/version.py

Fix generating kickstart

---

packaging/preupgrade-assistant.spec
preupg/version.py

New minor version due to change to API in commit 34cb3c1.

Bump version to 2.3.0

---

packaging/sources/preupgrade-assistant-python-2.4.patch
packaging/sources/preupgrade-assistant-six.patch
preupg/application.py
preupg/exception.py
preupg/report_parser.py
preupg/script_api.py
preupg/settings.py
preupg/xmlgen/compose.py
sdist
tools/preupg-create-group-xml
tools/preupg-xccdf-compose

Exit instead of continue if XML template not found.
Make exceptions more verbose.
Another minor cleanup:
- code wrap on 80 chars
- classmethod to staticmethod, where classmethod not needed
- fixed typos
- removed unused imports or variables

Minor cleanup

---

doc/README
preupg/application.py
preupg/report_parser.py
preupg/settings.py
preupg/xmlgen/xml_tags.py
preupg/xmlgen/xml_utils.py

result-admin.xml/html, result-user.xml/html are reduntant in PA because
the final result is the same as in the default result.xml/html

Remove creation of admin and user reports

---

packaging/sources/crossarch_migration_support_check.patch
preupg/application.py
preupg/cli.py
preupg/common.py
preupg/conf.py
preupg/creator/application.py
preupg/creator/conf.py
preupg/creator/ui_helper.py
preupg/kickstart/application.py
preupg/kickstart/conf.py
preupg/kickstart/plugins/packages.py
preupg/kickstart/plugins/partitioning.py
preupg/kickstart/plugins/repos.py
preupg/kickstart/plugins/users_groups.py
preupg/logger.py
preupg/report_parser.py
preupg/utils.py
preupg/xccdf.py
preupg/xml_manager.py
preupg/xmlgen/compose.py
preupg/xmlgen/oscap_group_xml.py
preupg/xmlgen/script_utils.py
preupg/xmlgen/xml_utils.py

- replaced using six library by python built-in functions
- the code without six is still python 2.x and 3.x compatible
- remove unused imports, commented out code
- wrap code to 80 chars
- functionality is kept the same

Basic code cleanup

---

preupg/xmlgen/compose.py
preupg/xmlgen/oscap_group_xml.py
preupg/xmlgen/script_utils.py
preupg/xmlgen/xml_utils.py
tests/test_xml.py
tools/preupg-create-group-xml

- simplify loading and parsing INI files
- rename strangely named variables
- fix checking whether required fields are in INI
- update unit tests and patch accordingly

xmlgen refactoring

---

packaging/sources/crossarch_migration_support_check.patch

The patch was not possible to apply do to previous changes merged to master.

Update crossarch patch

---

tests/test_example.py
tests/test_preupg_diff.py

- add a simple example of a unit tests
- propose unit test conventions
- update preupg_diff tests to match the conventions

Add basic example of writing unit tests

---

preupg/ui/templates/report/hostrun_confirm_delete.html
preupg/ui/templates/report/hostrun_delete_older.html
preupg/ui/templates/report/hostrun_delete_selected.html
preupg/ui/templates/report/runs.html

- related RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1244881

UI to show report finish time, not upload time

---

doc/module_writing_tutorial/README.md

There was no document describing how to create new custom module set.
This README describes the process that is yet to be implement in the PR #233.

New module set tutorial README

---

packaging/preupgrade-assistant.spec
setup.py

- add module writing tutorial to the RPM

Move READMEs to /usr/share/doc

---

doc/module_writing_tutorial/04_fix_issue/check

fix syntax error in module tutorial 04_fix_issue

---

preupg/cli.py
preupg/logger.py
preupg/utils.py

A spontaneous followup to #313.
These functions and class are nor part of public API nor are they
mentioned anywhere else in the project (checked using `grep -r`.)

Remove dead functions and classes

---

preupg/application.py

Before, when _--upload_, _--riskcheck_ or --cleanup was used with no module set in _/usr/share/preupgrade_, the Preupgrade Assistant failed, as it was trying to find any module set. However no module set is needed for these two options, they are supposed to work solely with the latest assessment result.
Resolves https://github.com/upgrades-migrations/preupgrade-assistant/issues/320

Allow certain operations without module set present

---

packaging/preupgrade-assistant.spec

Unwrapped, the text will fold unpredictably (ie. in the middle of a wo
rd,) at any terminal width.

Keep %description wrapped to ~80 characters
